json.id child.id
json.parent_id child.parent_id
json.name child.name
json.username child.username
json.birthdate child.birthdate
json.points_available child.points_available
json.money_banked child.money_banked
json.chores child.chores
json.child_chores child.child_chores